### ISSUE TITLE
Viewer Count - Change "BobRoss" -> "sardoche"

### ISSUE THREAD

**Issue by FOXCraft40** [kevinleguillou/sardtv#1]
For correct viewer count :
    In `Twitch_Api.js` :  
       replace `user_login=bobross` by `user_login=sardoche`

**Comment by Zenrac** [comment]
Fixed by [commit 1d9a77d](https://github.com/kevinleguillou/sardtv/commit/1d9a77d93dc9015697bed6e7d3e0a35ca637c215). 

Can be closed.

**Comment by kevinleguillou** [comment]
Vous êtes au taquet haha. J'ai push sans faire gaffe à cette URL de test, mais c'est fix.
